env:
  jest: true
  node: true
parser: "@babel/eslint-parser"
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - import
rules:
  import/extensions:
    - error
    - js: never
      ignorePackages: true
